- name: Patch and reboot servers
  hosts: localhost
  vars:
    api_key: !vault |
             $ANSIBLE_VAULT;1.1;AES256
             39313136366236313839613565386663306262653033633230313537626566326139646361643437
             3331373164383032353832646162613037376132356336340a306232333161663931666665666438
             34633561323361623238336637656136643761336431323039326330343761623436666135346639
             3735366464663531390a653032356631663766373433303065323633626439336232383461333234
             36646637333833636364643565393231626161343061306537393337613836356362

  tasks:
     - name: Run a script with arguments (free form)
       script: updateactiveGates.py {{ api_key }}
       args:
         executable: python3
       register: result_status
       when: ansible_distribution == "Amazon" or ansible_os_family == "Redhat"

     - debug:
        var: result_status
